
/**
 *Title:             Colors choose
 * Files:            ColorChooseFrame.java
 * Semester:         LAB Desk Summer- Block 5 2021
 * Author:           TuyenNH
 * Email:            tuyennhhe141159@fpt.edu.vn
 * CS Login:         User
 * Lecturer's Name:  DuongTB
 * Lab Section:      4
 */
import java.awt.Color;
import java.awt.Label;
import javax.swing.JRadioButton;

/**
 *
 * @author User
 */
public class ColorChooseFrame extends javax.swing.JFrame {

    /**
     * Creates new form ColorChooseFrame
     */
    public ColorChooseFrame() {
        initComponents();
        //set default color, when open program
        radioGreen.setSelected(true);
        labelColor.setText("Green is selected");
        panelColor.setBackground(Color.green);

        //set tile
        this.setTitle("Color choose");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        radioRed = new javax.swing.JRadioButton();
        radioGreen = new javax.swing.JRadioButton();
        radioBlue = new javax.swing.JRadioButton();
        radioBlack = new javax.swing.JRadioButton();
        panelColor = new javax.swing.JPanel();
        labelColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(radioRed);
        radioRed.setText("Red");
        radioRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRedActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioGreen);
        radioGreen.setText("Green");
        radioGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGreenActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBlue);
        radioBlue.setText("Blue");
        radioBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBlueActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBlack);
        radioBlack.setText("Black");
        radioBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBlackActionPerformed(evt);
            }
        });

        panelColor.setBackground(new java.awt.Color(204, 204, 204));

        labelColor.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelColorLayout = new javax.swing.GroupLayout(panelColor);
        panelColor.setLayout(panelColorLayout);
        panelColorLayout.setHorizontalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelColorLayout.setVerticalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelColor, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioRed)
                    .addComponent(radioGreen)
                    .addComponent(radioBlue)
                    .addComponent(radioBlack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(radioRed)
                .addGap(26, 26, 26)
                .addComponent(radioGreen)
                .addGap(30, 30, 30)
                .addComponent(radioBlue)
                .addGap(26, 26, 26)
                .addComponent(radioBlack)
                .addGap(37, 37, 37)
                .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Event when click radio button red
     *
     * @param evt
     */
    private void radioRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRedActionPerformed
        labelColor.setText("Red is selected");
        panelColor.setBackground(Color.red);
    }//GEN-LAST:event_radioRedActionPerformed
    /**
     * Event when click radio button green
     *
     * @param evt
     */
    private void radioGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGreenActionPerformed
        labelColor.setText("Green is selected");
        panelColor.setBackground(Color.green);
    }//GEN-LAST:event_radioGreenActionPerformed
    /**
     * Event when click radio button blue
     *
     * @param evt
     */
    private void radioBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBlueActionPerformed
        labelColor.setText("Blue is selected");
        panelColor.setBackground(Color.blue);
    }//GEN-LAST:event_radioBlueActionPerformed
    /**
     * Event when click radio button black
     *
     * @param evt
     */
    private void radioBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBlackActionPerformed
        labelColor.setText("Black is selected");
        panelColor.setBackground(Color.black);
    }//GEN-LAST:event_radioBlackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorChooseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorChooseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorChooseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorChooseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorChooseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel labelColor;
    private javax.swing.JPanel panelColor;
    private javax.swing.JRadioButton radioBlack;
    private javax.swing.JRadioButton radioBlue;
    private javax.swing.JRadioButton radioGreen;
    private javax.swing.JRadioButton radioRed;
    // End of variables declaration//GEN-END:variables
}
