
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class MyFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
         // call function to set color for panel  
        stateChange();
        /**
         * display value of slider
         */
        txtRed.setText("R = " + Integer.toString(jSRed.getValue()));
        txtGreen.setText("G = " + Integer.toString(jSGreen.getValue()));
        txtBlue.setText("B = " + Integer.toString(jSBlue.getValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPColor = new javax.swing.JPanel();
        txtBlue = new javax.swing.JTextField();
        jSBlue = new javax.swing.JSlider();
        txtGreen = new javax.swing.JTextField();
        txtRed = new javax.swing.JTextField();
        jSRed = new javax.swing.JSlider();
        jSGreen = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPColorLayout = new javax.swing.GroupLayout(jPColor);
        jPColor.setLayout(jPColorLayout);
        jPColorLayout.setHorizontalGroup(
            jPColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPColorLayout.setVerticalGroup(
            jPColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtBlue.setEditable(false);
        txtBlue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBlue.setForeground(new java.awt.Color(0, 51, 255));
        txtBlue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSBlue.setBackground(new java.awt.Color(238, 238, 238));
        jSBlue.setForeground(new java.awt.Color(255, 255, 255));
        jSBlue.setMaximum(255);
        jSBlue.setPaintTicks(true);
        jSBlue.setValue(84);
        jSBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSBlueStateChanged(evt);
            }
        });

        txtGreen.setEditable(false);
        txtGreen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGreen.setForeground(new java.awt.Color(102, 255, 102));
        txtGreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtRed.setEditable(false);
        txtRed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRed.setForeground(new java.awt.Color(255, 51, 51));
        txtRed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSRed.setBackground(new java.awt.Color(238, 238, 238));
        jSRed.setForeground(new java.awt.Color(255, 255, 255));
        jSRed.setMaximum(255);
        jSRed.setPaintLabels(true);
        jSRed.setPaintTicks(true);
        jSRed.setSnapToTicks(true);
        jSRed.setValue(57);
        jSRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSRedStateChanged(evt);
            }
        });

        jSGreen.setBackground(new java.awt.Color(238, 238, 238));
        jSGreen.setForeground(new java.awt.Color(255, 255, 255));
        jSGreen.setMaximum(255);
        jSGreen.setPaintTicks(true);
        jSGreen.setValue(180);
        jSGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSGreenStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSBlue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSGreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSRed, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRed, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSRed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSGreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBlue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSBlue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * set color and value for panel and textfiled
     */
    private void stateChange() {
        /**
         * get value of jslider and set color for panel
         */
        int blue = jSBlue.getValue();
        int green = jSGreen.getValue();
        int red = jSRed.getValue();
        Color color = new Color(red, green, blue);
        jPColor.setBackground(color);
    }
    private void jSBlueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSBlueStateChanged
         // call function to set color for panel           
        stateChange();
        // display value of slider        
        txtBlue.setText("B = " + Integer.toString(jSBlue.getValue()));
    }//GEN-LAST:event_jSBlueStateChanged

    private void jSRedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSRedStateChanged
        // call function to set color for panel    
        stateChange();
        // display value of slider       
        txtRed.setText("R = " + Integer.toString(jSRed.getValue()));
    }//GEN-LAST:event_jSRedStateChanged

    private void jSGreenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSGreenStateChanged
         // call function to set color for panel      
        stateChange();
        //display value of slider
        txtGreen.setText("G = " + Integer.toString(jSGreen.getValue()));
    }//GEN-LAST:event_jSGreenStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPColor;
    private javax.swing.JSlider jSBlue;
    private javax.swing.JSlider jSGreen;
    private javax.swing.JSlider jSRed;
    private javax.swing.JTextField txtBlue;
    private javax.swing.JTextField txtGreen;
    private javax.swing.JTextField txtRed;
    // End of variables declaration//GEN-END:variables
}
