/**
 *Title:          Use JFormatTextField
Files:            JFormatTextFieldFrame.java
Semester:         LAB Desk Summer- Block 5 2021
Author:           TuyenNH
Email:            tuyennhhe141159@fpt.edu.vn
CS Login:         User
Lecturer's Name:  DuongTB
Lab Section:      4
 */
import java.text.SimpleDateFormat;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class JFormatTextFiledFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFormatTextFiledFrame
     */
    public JFormatTextFiledFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        formatTxtCurrency = new javax.swing.JFormattedTextField();
        formatTxtTime = new javax.swing.JFormattedTextField();
        formatTxtPercent = new javax.swing.JFormattedTextField();
        lbFormat = new javax.swing.JLabel();
        formatTxtNumber = new javax.swing.JFormattedTextField();
        formatTxtDate = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Date");

        jLabel3.setText("Currency");

        jLabel4.setText("Time");

        jLabel5.setText("Percent");

        jLabel1.setText("Number");

        formatTxtCurrency.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("$#,##0.00"))));
        formatTxtCurrency.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formatTxtCurrencyFocusGained(evt);
            }
        });

        formatTxtTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("h:mm:ss a"))));
        formatTxtTime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formatTxtTimeFocusGained(evt);
            }
        });

        formatTxtPercent.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getPercentInstance())));
        formatTxtPercent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formatTxtPercentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formatTxtPercentFocusLost(evt);
            }
        });

        lbFormat.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        formatTxtNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        formatTxtNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formatTxtNumberFocusGained(evt);
            }
        });

        formatTxtDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));
        formatTxtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formatTxtDateFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(78, 78, 78))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(97, 97, 97)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(72, 72, 72)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(80, 80, 80)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formatTxtPercent, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(formatTxtTime)
                            .addComponent(formatTxtCurrency)
                            .addComponent(formatTxtNumber)
                            .addComponent(formatTxtDate))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(formatTxtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(formatTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatTxtCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formatTxtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(formatTxtPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
     * Event when enter value in Currency textfiled
     *
     * @param evt
     *
     * No return
     */
    private void formatTxtCurrencyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatTxtCurrencyFocusGained
        formatTxtCurrency.setText("$");
        lbFormat.setText("Enter number!");
    }//GEN-LAST:event_formatTxtCurrencyFocusGained
    /**
     * Event when leave away percent textfield
     *
     *
     * No return
     *
     * @param evt
     */
    private void formatTxtPercentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatTxtPercentFocusLost
        formatTxtPercent.setText(formatTxtPercent.getText() + "%");
    }//GEN-LAST:event_formatTxtPercentFocusLost
    /**
     * Event when enter value percent textfield
     *
     *
     * No return
     *
     * @param evt
     */
    private void formatTxtPercentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatTxtPercentFocusGained
        lbFormat.setText("Enter number!");
        formatTxtPercent.setText("");
    }//GEN-LAST:event_formatTxtPercentFocusGained

   /**
     * Event when enter value in time textfield
     *
     * No return
     *
     * @param evt
     */
    private void formatTxtTimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatTxtTimeFocusGained
        lbFormat.setText("Enter time! Format: h:mm:ss a");
    }//GEN-LAST:event_formatTxtTimeFocusGained

    private void formatTxtNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatTxtNumberFocusGained
       lbFormat.setText("Enter number!");
    }//GEN-LAST:event_formatTxtNumberFocusGained

    private void formatTxtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatTxtDateFocusGained
         lbFormat.setText("Enter date! Format: MM/dd/yyyy");
    }//GEN-LAST:event_formatTxtDateFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormatTextFiledFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormatTextFiledFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormatTextFiledFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormatTextFiledFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormatTextFiledFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField formatTxtCurrency;
    private javax.swing.JFormattedTextField formatTxtDate;
    private javax.swing.JFormattedTextField formatTxtNumber;
    private javax.swing.JFormattedTextField formatTxtPercent;
    private javax.swing.JFormattedTextField formatTxtTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbFormat;
    // End of variables declaration//GEN-END:variables
}
